### ISSUE TITLE
[BUG] CORS error from localhost

### ISSUE THREAD

**Issue by Soleone** [SuspiciousLookingOwl/youtubei#10]
**Describe the bug**

I'm trying this library out for the first time and I'm running into a cross origin resource sharing error in my browser (Brave, privacy shields disabled):

> Access to fetch at 'https://www.youtube.com/watch?v=wEVit5lILno&pbj=1' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> www.youtube.com/watch?v=wEVit5lILno&pbj=1:1 Failed to load resource: net::ERR_FAILED
> asyncToGenerator.js?1da1:6 Uncaught (in promise) TypeError: Failed to fetch 

**To Reproduce**

The code I am using in my Vue app running on localhost:

```
import { Client } from "youtubei"

const youtube = new Client()

(async () => {
  const video = await youtube.getVideo("wEVit5lILno")
  console.log(video)
})()
```

**Expected behavior**

I was expecting this to just work, or alternatively the documentation to call this out in some way and if there are workarounds.

**Additional context**

* Is this only a problem on localhost?
* Am I doing something wrong? Should there have been an additional set up step?
* Is this same request expected to work in production when deployed to a real URL? Is only localhost not allowed?

**Comment by SuspiciousLookingOwl** [comment]
This is expected as the library is using an unofficial Youtube API and it doesn't allow CORS request from different origin than `youtube.com`

The only solution (for now) is to create a NodeJS API that acts as a middleman between your frontend app and Youtube server.

For example, create a [express](https://expressjs.com/) app:

```js
const express = require('express')
const { Client } = require('youtubei')
const app = express()
const port = 3000

const youtube = new Client()

app.get('/:videoId', async (req, res) => {
  // this might not work due to circular dependency, but this is just an example.
  res.send(await youtube.getVideo(req.params.videoId));
})

app.listen(port, () => {})
```

And send a request to your backend server instead of using `youtubei` on your Vue app.

---

> Is this only a problem on localhost?

No, this should happen on any origin if you are sending a request from outside of `youtube.com`

> Am I doing something wrong? Should there have been an additional set up step?

No, this error is expected.

> Is this same request expected to work in production when deployed to a real URL? Is only localhost not allowed?

No, see the first answer.
