### ISSUE TITLE
getVideo return undefined

### ISSUE THREAD

**Issue by FaxBRz** [SuspiciousLookingOwl/youtubei#103]
**Describe the bug**
getVideo return undefined

**To Reproduce**
Just using getVideo, it seems to have to do with my hosting IP
```
	const video = await youtube.getVideo("dQw4w9WgXcQ");
	console.log(video) // Return "undefined"
```
**Expected behavior**
Return undefined

**Screenshots**

**Additional context**
The error only occurs on my VPS hosting, "getVideo" returns undefined, but "search" works normally. I have a private website to download music from YouTube, which I've been using for a few days. Is there a chance that my machine's IP has been banned by YouTube? Many requests were made. I tested the same code on my personal machine, and it worked fine. Everything was working about 1-2 days ago.

**Comment by SuspiciousLookingOwl** [comment]
It is possible that your IP got blacklisted by YouTube, although I expected `.getVideo()` to throw an error instead of returning `undefined` if that's the case.  It will be hard for me to debug this since I also have youtubei running on a VPS and `.getVideo()` works just fine there. If it's caused by the IP blacklist, there's nothing much that I can do, unfortunately.

You can try using [`youtubei.js` ](https://www.npmjs.com/package/youtubei.js)'s `.getInfo(videoId)`, see if that's working for you, `youtubei.js` uses newer endpoint (`/player`) to get the video info, and `youtubei` uses older endpoint (`/watch`) to get the video info. If `getInfo` on `youtubei.js` works on your VPS, I'll try to update `.getVideo` so that it uses the newer endpoint instead

**Comment by FaxBRz** [comment]
Unfortunately, youtubei.js didn't work. I tested the same code on my VPS and my personal computer. On the VPS, it returned:
```
{
  "playability_status": {
    "status": "ERROR",
    "reason": "This video is unavailable",
    "embeddable": false,
    "audio_only_playablility": null,
    "error_screen": {
      "type": "PlayerErrorMessage",
      "subreason": [Text],
      "reason": [Text],
      "proceed_button": null,
      "thumbnails": [Array],
      "icon_type": "ERROR_OUTLINE"
    }
  }
}
```
While on my personal computer, it worked without any problems. I am using `/player`. I hadn't changed anything on the VPS before this issue appeared. I believe that the machine's IP has been blacklisted, which seems to be the only probable reason.

**Comment by SuspiciousLookingOwl** [comment]
I believe it's because of the IP blacklist too, in that case, there's nothing much I can do unfortunately.
If you think that the issue is caused by the library or if there's something that the library can do to fix it, feel free to reopen this issue or create a new one

**Comment by FaxBRz** [comment]
Yes, I agree with you. The problem was too many requests to the YouTube API, resulting in a ban. I managed to optimize the requests and reduce the risk of being banned. Thank you for the help. The problem wasn't the library but something on my end. Thank you for your help and time.
