### ISSUE TITLE
[BUG] Undefined on "getPlaylist()" ( mix )

### ISSUE THREAD

**Issue by Asgarrrr** [SuspiciousLookingOwl/youtubei#31]
**Expected behavior**
I don't know if it's a bug

**Screenshots**

<img width="476" alt="Capture d’écran 2021-09-26 à 15 04 56" src="https://user-images.githubusercontent.com/36574651/134809292-c6eeed5f-a168-46d6-8f10-8e05863d2f71.png">

<img width="809" alt="Capture d’écran 2021-09-26 à 15 05 15" src="https://user-images.githubusercontent.com/36574651/134809301-85ab1760-500a-48c4-8e60-3525eb91c327.png">

<img width="137" alt="Capture d’écran 2021-09-26 à 15 05 32" src="https://user-images.githubusercontent.com/36574651/134809311-d6d6e953-b017-4c8a-9e11-209a12301503.png">

**Comment by SuspiciousLookingOwl** [comment]
The issue template is there for a reason, please create a new issue with a **minimal** reproducible code to reproduce this bug. Giving a screenshot of the discord command isn't really helpful since I don't know what's actually being passed to the parameter when you are calling the `.getPlaylist()` method
