### ISSUE TITLE
[ENHANCEMENT] Examples on how to use cookies

### ISSUE THREAD

**Issue by EvasiveXkiller** [SuspiciousLookingOwl/youtubei#34]
**Is your feature request related to a problem? Please describe.**
429's are hard to avoid, cookies are one way to slow down the inevitable problem.

**Describe the solution you'd like**
Better documentation on how to use cookies, such as which format it accepts. 
Examples on how to use cookies from [node-ytdl-core](https://github.com/fent/node-ytdl-core/blob/40d0c54da10a12397ac63b0dd39ed27de4ff294b/example/cookies.js#L13) or [youtube-dl](https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl) would be a great addition.

Any additional info and examples on how to extract the cookies would be a great addition too.

Thank you.

**Comment by SuspiciousLookingOwl** [comment]
I implemented cookie support but I actually never tried whether it's working or not 😅 well it *should*

```ts
const youtube = new Client({
	cookie: "key1=value1; key2=value2; key3=value3",
});
```

I'm not sure what's the correct way to get the proper YouTube cookie

If you are using Chromium based browser, you can:
1. Open [youtube.com](https://www.youtube.com/)
2. Open dev tools (F12)
3. Go to `Console` tab, and run `document.cookie`
4. It should print out the cookie, then copy it to your code / use env variable

Or:
1. Open [youtube.com](https://www.youtube.com/)
2. Open dev tools (F12)
3. Go to `Network` tab, and type `/next` on filter
4. Click on any video on your feed
5. There should be one or two request to `next?key=xxx`, click it and open the headers tab
6. Find `Request Headers` > `cookie`, and copy the value to your code

Both of them contains different value, I'm not really sure which one is the correct one (I bet it's the second one because It's being send to YouTube server, but maybe first one works for you 🤷🏻‍♂️), I'm not sure how to test it either since I've never faced 429 error before. 

Please let me know the result if you ended up trying it 😄

**Comment by EvasiveXkiller** [comment]
I tried both of the ways and I can report that both seems to work for me. I will report once I hit 429's and I will try and see which one works. 

The second method seems promising as it seems to contain more data than the first one, but that maybe just I'm using a browser that I dont usually use to extract the cookies 😅. 

I will close this for now, if there is any updates I will report. Thank you for clarifying 😁

**Comment by EvasiveXkiller** [comment]
It seems to be only `getVideo`. The rest of the methods just run fine.

Below is a short segment that will always fails with the current 429's

```js

const { Client } = require("youtubei");
const ytLinkResolver = new Client({
    cookie: "cookie goes here"
});

ytLinkResolver.getVideo("https://www.youtube.com/watch?v=f5_wn8mexmM").then((video => {
    console.log(video)
}))
```

Catching the error just prints out the entire HTML captcha page.

**Comment by SuspiciousLookingOwl** [comment]
Do you get 429 both with and without cookies?

**Comment by EvasiveXkiller** [comment]
Yes, it seems to make no difference with or without cookies

**Comment by SuspiciousLookingOwl** [comment]
Can't reproduce with thise code
```js
import { Client } from "youtubei";

const youtube = new Client();
youtube.getVideo("https://www.youtube.com/watch?v=f5_wn8mexmM").then((video) => {
	console.log(video);
});
```
Are you using VPN, or running in a VPS? From my experience using VPN / running the code in a VPS can give me some 429s

**Comment by EvasiveXkiller** [comment]
>    Are you using VPN, or running in a VPS? From my experience using VPN / running the code in a VPS can give me some 429s

I'm not running with a VPN. I'm self-hosting the service that uses this lib and upon getting a new IP this problem goes away. 

>    Are you also getting 429 even though you are only sending one request?

Yes, I created a new project with just this lib and it will throw the exact same error.

**Comment by SuspiciousLookingOwl** [comment]
I just realized that the cookie is actually not being sent 😅 please try version `0.0.1-rc.27`

**Comment by SuspiciousLookingOwl** [comment]
I'm slightly confused with your last comment. What did you mean with `Home page` and `no login` / `logged in`?

**Comment by SuspiciousLookingOwl** [comment]
Ah I see, I will try to reproduce it.

A bit unrelated, but @SushiBtw said that using IPv6 might prevent rate limit (https://github.com/SuspiciousLookingOwl/youtubei/issues/14), never tried it before so I don't know if it's true or not. but worth to try
```js
new Client({
	requestOptions: {
		localAddress: "your:ipv6"
	}
})
```

**Comment by EvasiveXkiller** [comment]
I will look into IPv6 sooner or later, bit concerned about the rest of my infrastructure since I dont have anything that is on IPv6 yet. Seems cool and will let you know if I ever tried

**Comment by SushiBtw** [comment]
Using Hetzner IPv6/64 never got me rate-limited, I just roll a ipv6 from the table and sending every hour like 100 requests never limited me.
