### ISSUE TITLE
[ENHANCEMENT] Channel Subscribers Count

### ISSUE THREAD

**Issue by rafaeljustinox** [SuspiciousLookingOwl/youtubei#5]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to get the channel subscribers count.

**Describe alternatives you've considered**
Exploring the channel result

**Additional context**
No aplicable

**Comment by SuspiciousLookingOwl** [comment]
I wanted to add this when I first started making youtubei. Unfortunately getting the exact subscriber count (like video count) is not possible since Youtube returns literal string for the subscriber count without the exact number
![image](https://user-images.githubusercontent.com/32597776/111422679-a06b7700-8721-11eb-8044-eb1112b9be74.png)

I will probably just add the string as `subscriberCount` and let it be as is (just like video upload date). It's better than nothing

**Comment by rafaeljustinox** [comment]
Thanks for answering! Yeah! It's better then nothing. Is there another way to get the exacly number without using the Youtube oficial API? I mean, using another API unofficial?

**Comment by SuspiciousLookingOwl** [comment]
Not to my knowledge.
