### ISSUE TITLE
Youtube shorts is not working fine, it donot return the next page youtube shorts, and also the view count of shorts is not accurate

### ISSUE THREAD

**Issue by Erarshad** [SuspiciousLookingOwl/youtubei#86]
when ever fetching the youtube shorts from channel, i am not getting the next page shorts, also i am not getting the right view count of youtube shorts.

**Comment by SuspiciousLookingOwl** [comment]
Can't replicate, I'm able to fetch next shorts page with this code
```ts
const result = await client.getChannel("UCXuqSBlHAE6Xw-yeJA0Tunw");
if (!result) return;

await result.shorts.next();
console.log(result.shorts.items.length);
await result.shorts.next();
console.log(result.shorts.items.length);
```

For the view count, seems like it is indeed not accurate, although I'm not sure how to proceed with this, since it seems like YouTube doesn't return the actual number of the view count (at least for the short endpoint on channel), instead it returns the formatted number (for example `338k views`, which will be incorrectly parsed to `338` by this library)

But it seems like it works fine if you use the `client.getVideo(SHORT_ID)` method (yes you can use `.getVideo` to get short information, it works the same).

It's a bit difficult trying to create a library that returns a consistent object type and value, since what YouTube uses on their page sometimes returns the formatted value that will be shown on the page instead of the actual / raw value. I will probably fix this later because I'm planning to rewrite some part of the code so it returns a more consistent result.
